### ISSUE TITLE
Silent failures in transaction when no PROCESS privilege

### ISSUE THREAD

**Issue by simonwistow** [mperham/deadlock_retry#4]
We recently found that we were dropping parts of transactions on the floor. The symptom was this error message

Deadlock detected on retry 1, restarting transaction
Cannot log innodb status: Mysql::Error: Access denied; you need the PROCESS privilege for this operation: show innodb status

Whilst the error is rescued it would still mess up the transaction and, more importantly, would do so silently.

We fixed it by introducing a config option which controlled whether log_innodb_status was called or not (it's off by default) - a better solution may be to check for privileges somehow but it looks like that's not trivial and may introduce performance problems.

**Comment by mperham** [comment]
Fixed by GH-5.
