### ISSUE TITLE
'show innodb status' is now 'show engine innodb status' on mysql 5.5

### ISSUE THREAD

**Issue by ghazel** [mperham/deadlock_retry#6]
Title says it all. 

From http://dev.mysql.com/doc/refman/5.1/en/show-engine.html 
"Older (and now deprecated) synonyms are SHOW INNODB STATUS for SHOW ENGINE INNODB STATUS and SHOW MUTEX STATUS for SHOW ENGINE INNODB MUTEX. SHOW INNODB STATUS and SHOW MUTEX STATUS are removed in MySQL 5.5."

**Comment by jspooner** [comment]
Looks like this was fixed in v1.1.2?

== v1.1.2
- Exponential backoff, sleep 0, 1, 2, 4... seconds between retries.
- Support new syntax for InnoDB status in MySQL 5.5.
